spring.application.name=spring-ai-open-ai

logging.level.org.springframework.web=DEBUG
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini

spring.ai.openai.image.options.model=gpt-image-1

server.port=8081