spring.application.name=spring-ai-open-ai

logging.level.org.springframework.web=DEBUG
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o-mini

spring.ai.openai.image.options.model=gpt-image-1

server.port=8081

spring.ai.vectorstore.pgvector.index-type=hnsw
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.max-document-batch-size=1000

spring.datasource.password=postgres
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/ics

spring.sql.init.mode=always
spring.jpa.show-sql=true